# Generated by Django 3.2.15 on 2022-09-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
