# Generated by Django 3.2.15 on 2022-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapp', '0002_item_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cod',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
