# Generated by Django 3.2.15 on 2022-12-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapp', '0003_item_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cod',
            new_name='code',
        ),
    ]
